server:
  port: 8300

spring:
  application:
    name: mall-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.39.118:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: sql123456
  main:
    allow-circular-references: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 自动自增id
  global-config:
    db-config:
      id-type: auto
