server:
  port: 8200
spring:
  application:
    name: mall-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.39.118:3306/mall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: sql123456

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 自动自增id
  global-config:
    db-config:
      id-type: auto
