server:
  port: 8400

spring:
  application:
    name: mall-ware
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.39.118:3306/mall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: sql123456
  main:
    allow-circular-references: true

  jackson:
    date-format: yyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 自动自增id
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.lny.mall.ware: debug