server:
  port: 9999

spring:
  application:
    name: mall-gateway

  cloud:
    gateway:
      routes:
        - id: mall-ware
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            # 路径重写
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: mall-member
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            # 路径重写,把对应的api路径，重新成product
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            # 路径重写,把对应的api路径，重新成product
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: mall-third-party
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*),/$\{segment}

        - id: admin_ruote
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            # 路径重写,把对应的api路径，重新成renren-fast
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}

        - id: test_baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: test_qq
          uri: https://www.qq.com
          predicates:
            - Query=url,qq